version: "3.3"
services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - test-db-vol:/var/lib/postgresql/data

  db-manager:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5000:80"

  backend:
    build: .
    ports:
      - "1234:1234"

  static:
    image: nginx:1.13.5-alpine
    volumes:
      - ./web:/usr/share/nginx/html
      - ./student-images:/usr/share/nginx/student-images
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"

volumes:
  test-db-vol:
    external: true