version: "3.3"
services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - test-db-vol:/var/lib/postgresql/data

  backend:
    build: .

  static:
    image: nginx:1.13.5-alpine
    volumes:
      - ./web:/usr/share/nginx/html
      - ./student-images:/usr/share/nginx/student-images
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"

volumes:
  test-db-vol:
    external: true